#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-PointGroup-C6v
version:      0.01
version_from: C6v.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
